### ISSUE TITLE
请问有intel mac的版本吗？

### ISSUE THREAD

**Issue by lightfront** [sojourners/public-Xiangqi#11]

**Comment by sojourners** [comment]
手上没intel的mac暂时打包不了，过两天我看看

**Comment by sojourners** [comment]
https://github.com/sojourners/public-Xiangqi/releases，下载tchess_V1.4_macos_x64.dmg

**Comment by lightfront** [comment]
请问能为1.7版本编译一个intel mac版吗？谢谢！

**Comment by sojourners** [comment]
https://github.com/sojourners/public-Xiangqi/releases/tag/V1.7
现在用intel mac的很少了吧，你是老机器吗，还是黑苹果？

**Comment by lightfront** [comment]
谢谢你！我是老机器
