### ISSUE TITLE
Issue with Chess Engine Recalculating from Scratch After Each Move in a FEN Position

### ISSUE THREAD

**Issue by leonwerth2703** [sojourners/public-Xiangqi#12]
There is a feature that I think is missing: when I have a chess position (FEN) that the engine takes 30 seconds to solve, and then I make the next move, the engine immediately starts solving the position from scratch as if it had not already solved it. This causes the engine to lose an advantage because even if it has found a good plan for a specific position, it recalculates everything after the next move, leading to unnecessary time loss and reducing the engine's strength in fast or complex games.

**Comment by sojourners** [comment]
I don't understand your question, the engine calculates each step based on the latest situation, passing in both fen as well as moves

**Comment by leonwerth2703** [comment]
https://github.com/user-attachments/assets/7f43b26c-5364-47ed-acf2-02b9bdcaaff2

I'm using the Pikafish version from 26-12-2022 on purpose, as older versions are slightly weaker. This position normally takes the engine about 30 seconds to evaluate, and it initially rates move S5.6 as 1000 points better. However, once I play S5.6, the engine's evaluation drops to only 60 points. This is odd, as it had already calculated a significant advantage before. If I were to let it think for another 30 seconds, it would likely return to the original evaluation. But as soon as I make the move, the engine starts from scratch again.

**Comment by leonwerth2703** [comment]
https://github.com/user-attachments/assets/ca7bcb4a-96f1-4de4-8d62-087018ab9b1e

This is Sharkchess 1.8, also using Pikafish véion 26-12-2022

**Comment by sojourners** [comment]
Got it, it seems like the hash table is not working. I will fix it in the next version. Thanks for the feedback.
