### ISSUE TITLE
macos版本

### ISSUE THREAD

**Issue by atopx** [sojourners/public-Xiangqi#3]
我在mac上编译后不能用，发现macos连线代码空着的，希望可以优先补充一下，可以先搞基本的识别功能

提供下思路：
- **get window activate winid**: https://developer.apple.com/documentation/coregraphics/quartz_window_services
- **get window screenshot command**：`screencapture -x -l {window_id} {output.png}`

有需要的话我可以提供帮助，我用python在mac环境下实现过终端版本半成品功能

**Comment by sojourners** [comment]
是的，Macos 连线部分尚未实现。不过连线器的核心逻辑都是复用的，理论上你只要实现MacosGraphLinker 中的方法就可以完成mac 连线。
