### ISSUE TITLE
不缩放识别不了

### ISSUE THREAD

**Issue by GuoJuna** [sojourners/public-Xiangqi#6]
不缩放识别不了,请问要修改的话,需要调整那部分代码?

**Comment by sojourners** [comment]
可以详细debug一下AbstractGraphLinker。识别不了与棋盘的清晰度也有关，我测试的1080p不缩放和4k缩放都可以正常识别。

**Comment by yanlongbinluck** [comment]
天天象棋，4k 200%缩放无法识别，100%缩放可以

**Comment by sojourners** [comment]
最新代码已解决wnidows下的分辨率缩放问题
